### ISSUE TITLE
better time management ?

### ISSUE THREAD

**Issue by tissatussa** [DkeRee/Trinket#75]
i just compiled your newest source on Linux. Then i let Trinket v4.0.0 play a game in CuteChess against another engine, about same rating, using tc 3 minutes + 10 seconds bonus. Trinket won the game, but it ended with more then 6 minutes on its clock ..

i guess the engine could have used more time each move, resulting in better play, reaching higher depths ? Maybe my 10 sec bonus was not interpreted properly ? Trinket never used more then 9 seconds for a move ..

**Comment by DkeRee** [comment]
I have made a lot of changes to it! Thanks!

**Comment by tissatussa** [comment]
@DkeRee great! can i test this newest version ?
